import { useTitle } from "../hooks/useTitle";
import { changelog } from "../data/changelog";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function Changelog() {
  useTitle("Changelog");

  return (
    <div>
      <header className="mb-10">
        <h1 className="font-serif italic text-5xl md:text-6xl tracking-tight mb-4">
          <span className="gradient-text-animated">Changelog</span>
        </h1>
        <p className="text-lg text-stone-500 dark:text-zinc-400 leading-relaxed">
          A running log of changes to this site. Entries are generated by
          Claude from each commit's diff — so some might be a bit off!
        </p>
      </header>

      <div>
        {/* Timeline rail on the left, entries stacked down the right. */}
        <div className="relative border-l border-stone-200 dark:border-zinc-700/60 pl-5 md:pl-7 space-y-6">
          {changelog.map((entry, i) => (
            <article key={i} className="relative">
              <span
                aria-hidden="true"
                className="absolute -left-[25px] md:-left-[33px] top-[7px] w-2 h-2 rounded-full bg-orange-400 ring-4 ring-[#faf8f5] dark:ring-zinc-900"
              />
              <div className="text-[10px] font-semibold uppercase tracking-[0.18em] text-stone-400 dark:text-zinc-500">
                {formatDate(entry.date)}
              </div>
              <h2 className="mt-1 font-serif italic text-lg md:text-xl text-stone-900 dark:text-zinc-50 leading-snug">
                {entry.title}
              </h2>
              <p className="mt-1 text-sm text-stone-600 dark:text-zinc-300 leading-relaxed">
                {entry.summary}
              </p>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}
